# This is a sample build configuration for Clojure.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: clojure:lein-2.7.1
clone:
  depth: full
pipelines:
  default:
    - step:
        name: Run Tests
        script:
          - lein doo phantom test once
    - step:
        name: Build uberjar
        script: 
          - lein clean uberjar 
    - step:
        name: Deploy to Heroku
        deployment: production
        script:
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
